name: SAST Scan with Snyk

on:
  workflow_dispatch:

jobs:
  sast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Set up Java 11
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Build Maven project
        run: mvn -B clean package -DskipTests
        
      - name: Install Snyk    
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk SAST scan
        run: snyk code test
